[build]
  command = "bun run build"
  publish = "output/out"
  environment = {
    NODE_VERSION = "20" # Ou "18" si vous préférez, mais assurez-vous de n'avoir que ceci sur la ligne
  }
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200